INCLUDE_ONCE_MACRO(LCMS)
SETUP_SUPERBUILD(LCMS)

ExternalProject_Add(LCMS
  PREFIX LCMS
  GIT_REPOSITORY https://github.com/LuaDist/lcms
  GIT_TAG f6473758511db915ff1762c4aa0115f5de414b3c
  SOURCE_DIR ${LCMS_SB_SRC}
  BINARY_DIR ${LCMS_SB_SRC}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  CMAKE_CACHE_ARGS ${SB_CMAKE_CACHE_ARGS}
  LOG_DOWNLOAD 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1
  )


