INCLUDE_ONCE_MACRO(ZLIB)

SETUP_SUPERBUILD(ZLIB)

# Try official release 1.2.8
ExternalProject_Add(ZLIB
  PREFIX ZLIB
  URL "http://downloads.sourceforge.net/project/libpng/zlib/1.2.3/zlib123.zip"
  URL_MD5 6465dd8f12d273c45b40048d7566e598
  BINARY_DIR ${ZLIB_SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_CACHE_ARGS ${SB_CMAKE_CACHE_ARGS}
  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
  ${CMAKE_SOURCE_DIR}/patches/ZLIB/CMakeLists.txt
  ${CMAKE_SOURCE_DIR}/patches/ZLIB/zconf.h.cmakein
  ${ZLIB_SB_SRC}
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  )

set(_SB_ZLIB_INCLUDE_DIR ${SB_INSTALL_PREFIX}/include)
if(WIN32)
  set(_SB_ZLIB_LIBRARY ${SB_INSTALL_PREFIX}/lib/zlib.lib)
elseif(UNIX)
  set(_SB_ZLIB_LIBRARY ${SB_INSTALL_PREFIX}/lib/libz${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()
