INCLUDE_ONCE_MACRO(GEOS)

SETUP_SUPERBUILD(PROJECT GEOS)

ExternalProject_Add(GEOS
  PREFIX GEOS
  URL "http://download.osgeo.org/geos/geos-3.4.2.tar.bz2"
  URL_MD5 fc5df2d926eb7e67f988a43a92683bae
  SOURCE_DIR ${GEOS_SB_SRC}
  BINARY_DIR ${GEOS_SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_CACHE_ARGS
  ${SB_CMAKE_CACHE_ARGS}
  -DBUILD_TESTING:BOOL=OFF
  -DGEOS_ENABLE_TESTS:BOOL=OFF
  CMAKE_COMMAND ${SB_CMAKE_COMMAND} )

SUPERBUILD_UPDATE_CMAKE_VARIABLES(GEOS FALSE)

SUPERBUILD_PATCH_SOURCE(GEOS)
