INCLUDE_ONCE_MACRO(ICONV)
SETUP_SUPERBUILD(ICONV)

ExternalProject_Add(ICONV
  PREFIX ICONV
  GIT_REPOSITORY https://github.com/LuaDist/libiconv
  GIT_TAG 0c4b6ef030e378684b3ec8985d9e87850bd5e7ff
  SOURCE_DIR ${ICONV_SB_SRC}
  BINARY_DIR ${ICONV_SB_SRC}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  CMAKE_CACHE_ARGS ${SB_CMAKE_CACHE_ARGS}
  LOG_DOWNLOAD 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1
  )


