if( __EXTERNAL_GEOS__)
  return()
else()
  set(__EXTERNAL_GEOS__ 1)
endif()

if(USE_SYSTEM_GEOS)
  message(STATUS "  Using GEOS system version")
  return()
endif()

SETUP_SUPERBUILD(PROJECT GEOS)
message(STATUS "  Using GEOS SuperBuild version")

ExternalProject_Add(GEOS
  PREFIX GEOS
  GIT_REPOSITORY "https://github.com/libgeos/libgeos"
  GIT_TAG 714127ef49087634e7f6687424fdf041d18c3d0f
  SOURCE_DIR ${GEOS_SB_SRC}
  BINARY_DIR ${GEOS_SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_CACHE_ARGS
  -DProject_WC_REVISION:STRING=99999
  -DBUILD_TESTING:BOOL=OFF
  -DGEOS_ENABLE_TESTS:BOOL=OFF
  CMAKE_COMMAND ${SB_CMAKE_COMMAND} )

SUPERBUILD_UPDATE_CMAKE_VARIABLES(GEOS FALSE)

SUPERBUILD_PATCH_SOURCE(GEOS)
