INCLUDE_ONCE_MACRO(MUPARSERX)

SETUP_SUPERBUILD(MUPARSERX)

package_require_cxx11(SHARK)

#Don't build muparserx examples
set(MUPARSERX_FLAGS)
list(APPEND MUPARSERX_FLAGS -DBUILD_EXAMPLES:BOOL=FALSE)

if(MSVC AND BUILD_SHARED_LIBS)
 list(APPEND MUPARSERX_FLAGS -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS:BOOL=TRUE)
endif()

ExternalProject_Add(MUPARSERX
  PREFIX MUPARSERX
  URL "https://github.com/beltoforion/muparserx/archive/v4.0.7.zip"
  URL_MD5 67819fc478436ea8f647c804e6f2e1a2
  BINARY_DIR ${MUPARSERX_SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  CMAKE_CACHE_ARGS ${SB_CMAKE_CACHE_ARGS} ${MUPARSERX_FLAGS}
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  DEPENDS ${MUPARSERX_DEPENDENCIES}
  #This patch is integrated in muparserx upstream but not yet released in 4.0.7
  UPDATE_COMMAND ${CMAKE_COMMAND} -E copy
  ${CMAKE_SOURCE_DIR}/patches/MUPARSERX/mpParserMessageProvider.cpp
  ${MUPARSERX_SB_SRC}/parser/
  )

SUPERBUILD_UPDATE_CMAKE_VARIABLES(MUPARSERX FALSE)

#Patch 
