INCLUDE_ONCE_MACRO(TINYXML)

SETUP_SUPERBUILD(PROJECT TINYXML)

ExternalProject_Add(TINYXML
  PREFIX TINYXML
  URL "http://sourceforge.net/projects/tinyxml/files/tinyxml/2.6.2/tinyxml_2_6_2.tar.gz/download"
  URL_MD5 c1b864c96804a10526540c664ade67f0
  BINARY_DIR ${TINYXML_SB_BUILD_DIR}
  INSTALL_DIR ${SB_INSTALL_PREFIX}
  DOWNLOAD_DIR ${DOWNLOAD_LOCATION}
  DEPENDS ${TINYXML_DEPENDENCIES}
  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
  ${CMAKE_SOURCE_DIR}/patches/TINYXML/CMakeLists.txt
  ${TINYXML_SB_SRC}
  CMAKE_CACHE_ARGS ${SB_CMAKE_CACHE_ARGS}
  CMAKE_COMMAND ${SB_CMAKE_COMMAND}
  )

SUPERBUILD_UPDATE_CMAKE_VARIABLES(TINYXML FALSE)
