extern int otb_6s_os_(
  otb_6s_integer *iaer_prof__,
  otb_6s_real *tamoy,
  otb_6s_real *trmoy,
  otb_6s_real *pizmoy,
  otb_6s_real *tamoyp,
  otb_6s_real *trmoyp,
  otb_6s_real *palt,
  otb_6s_real *phirad,
  otb_6s_integer *nt,
  otb_6s_integer *mu,
  otb_6s_integer *np,
  otb_6s_real *rm,
  otb_6s_real *gb,
  otb_6s_real *rp,
  otb_6s_real *xl,
  otb_6s_real *xlphim,
  otb_6s_integer *nfi,
  otb_6s_real *rolut
  );
