extern int v3p_netlib_os_(
  v3p_netlib_integer *iaer_prof__,
  v3p_netlib_real *tamoy,
  v3p_netlib_real *trmoy,
  v3p_netlib_real *pizmoy,
  v3p_netlib_real *tamoyp,
  v3p_netlib_real *trmoyp,
  v3p_netlib_real *palt,
  v3p_netlib_real *phirad,
  v3p_netlib_integer *nt,
  v3p_netlib_integer *mu,
  v3p_netlib_integer *np,
  v3p_netlib_real *rm,
  v3p_netlib_real *gb,
  v3p_netlib_real *rp,
  v3p_netlib_real *xl,
  v3p_netlib_real *xlphim,
  v3p_netlib_integer *nfi,
  v3p_netlib_real *rolut
  );
