extern int otb_6s_os_(
  otb_6s_integer *iaer_prof__,
  otb_6s_doublereal *tamoy,
  otb_6s_doublereal *trmoy,
  otb_6s_doublereal *pizmoy,
  otb_6s_doublereal *tamoyp,
  otb_6s_doublereal *trmoyp,
  otb_6s_doublereal *palt,
  otb_6s_doublereal *phirad,
  otb_6s_integer *nt,
  otb_6s_integer *mu,
  otb_6s_integer *np,
  otb_6s_doublereal *rm,
  otb_6s_doublereal *gb,
  otb_6s_doublereal *rp,
  otb_6s_doublereal *xl,
  otb_6s_doublereal *xlphim,
  otb_6s_integer *nfi,
  otb_6s_doublereal *rolut
  );
