#!/bin/bash
#PBS -N OTB_mpi
#PBS -l select=6:ncpus=12:mpiprocs=12:mem=45000mb:os=rh7
#PBS -l walltime=04:00:00

# Chargement des modules
module load cmake/3.4.3 openmpi/1.10.2 otb/develop-ptmp

# nombre de coeurs de calcul
nb_procs=`wc -l $PBS_NODEFILE | cut -d" " -f 1`

# deplacement dans le repertoire d'execution
# PBS_O_WORKDIR correspond au répertoire depuis lequel la commande qsub est lancée
cd $PBS_O_WORKDIR

mkdir -p /ptmp/sarrazie/ouput72

# lancement du programme mpi
mpirun -np $nb_procs --hostfile $PBS_NODEFILE  /ptmp/sarrazie/modules/install/rh7/otb/develop/lib/cmake/OTB-5.3/bin/otbMPIModuleTestDriver otbMPIBundleToPerfectSensorTest /ptmp/sarrazie/FCGC600084160/IMG_PHR1B_P_001/IMG_PHR1B_P_201310091304155_SEN_685561101-001_R1C1.JP2 /ptmp/sarrazie/FCGC600084160/IMG_PHR1B_MS_003/IMG_PHR1B_MS_201310091304155_SEN_685561101-003_R1C1.JP2 /ptmp/sarrazie/output72/imageMPIBundleToPerfectSensorTestNb72.tif
