TOPDIR = ..
include $(TOPDIR)/Make/makedirdefs
include $(TOPDIR)/Make/makedefs

DIRS = simplethreader\
       workcrew \
	$(NULL)

include $(TOPDIR)/Make/makedirrules
include $(TOPDIR)/Make/docrules
include $(TOPDIR)/Make/instrules
include $(TOPDIR)/Make/distrules
include $(TOPDIR)/Make/helprules
