@echo off
set CURRENT_SCRIPT_DIR=%~dp0

set PATH=%CURRENT_SCRIPT_DIR%bin;%PATH%
set GDAL_DATA=%CURRENT_SCRIPT_DIR%share\gdal
set GEOTIFF_CSV=%CURRENT_SCRIPT_DIR%share\epsg_csv
set LC_NUMERIC=C
set PYTHONPATH=%CURRENT_SCRIPT_DIR%lib\python;%PYTHONPATH%

set NEW_APP_PATH=%CURRENT_SCRIPT_DIR%lib\otb\applications
if "%OTB_APPLICATION_PATH%" == "" (
set OTB_APPLICATION_PATH=%NEW_APP_PATH%
) else (
echo.%OTB_APPLICATION_PATH% | findstr /C:"%NEW_APP_PATH%">nul || (
  set OTB_APPLICATION_PATH=%NEW_APP_PATH%;%OTB_APPLICATION_PATH%
)
)
set NEW_APP_PATH=
