#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbFlexibleDistanceWithMissingValue);
  REGISTER_TEST(otbImageAndVectorImageOperationFilterNew);
  REGISTER_TEST(otbImagePCAShapeModelEstimatorTest);
  REGISTER_TEST(otbFunctionToImageFilter);
  REGISTER_TEST(otbExtractROI2);
  REGISTER_TEST(otbComplexToVectorImageCastFilterNew);
  REGISTER_TEST(otbComplexToVectorImageCastFilterTest);
  REGISTER_TEST(otbMultiChannelExtractROI);
  REGISTER_TEST(otbVectorImageLegacyTest);
  REGISTER_TEST(otbVectorImageTest);
  REGISTER_TEST(otbExtractROITestMetaData);
  REGISTER_TEST(otbTestMultiExtractMultiUpdate);
  REGISTER_TEST(otbExtractROI);
  REGISTER_TEST(otbFunctionToImageFilterNew);
  REGISTER_TEST(otbVectorImageToASImageAdaptorNew);
  REGISTER_TEST(otbImageAndVectorImageOperationFilterTest);
  REGISTER_TEST(otbImageOfVectorsToMonoChannelExtractROI);
  REGISTER_TEST(otbImageOfVectorsToMonoChannelExtractROINew);
  REGISTER_TEST(otbExtractROINew);
  REGISTER_TEST(otbExtractROI_RGB);
  REGISTER_TEST(otbComplexToIntensityFilterTest);
  REGISTER_TEST(otbMultiToMonoChannelExtractROINew);
  REGISTER_TEST(otbMultiToMonoChannelExtractROI);
  REGISTER_TEST(otbImageTest);
  REGISTER_TEST(otbFlexibleDistanceWithMissingValueNew);
  REGISTER_TEST(otbImageFunctionAdaptorNew);
  REGISTER_TEST(otbImageFunctionAdaptor);
  REGISTER_TEST(otbMultiChannelExtractROINew);
}
