#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbImageListToVectorImageFilterNew);
  REGISTER_TEST(otbFlexibleDistanceWithMissingValue);
  REGISTER_TEST(otbImageAndVectorImageOperationFilterNew);
  REGISTER_TEST(otbImagePCAShapeModelEstimatorTest);
  REGISTER_TEST(otbStandardOneLineFilterWatcherTest);
  REGISTER_TEST(otbImageList);
  REGISTER_TEST(otbFunctionToImageFilter);
  REGISTER_TEST(otbImageListSourceNew);
  REGISTER_TEST(otbOssimElevManagerTest);
  REGISTER_TEST(otbExtractROI2);
  REGISTER_TEST(otbImageListToImageFilterNew);
  REGISTER_TEST(otbComplexToVectorImageCastFilterNew);
  REGISTER_TEST(otbComplexToVectorImageCastFilterTest);
  REGISTER_TEST(otbMultiChannelExtractROI);
  REGISTER_TEST(otbImageListToImageListApplyFilter);
  REGISTER_TEST(otbVectorImageLegacyTest);
  REGISTER_TEST(otbVectorImageTest);
  REGISTER_TEST(otbExtractROITestMetaData);
  REGISTER_TEST(otbTestMultiExtractMultiUpdate);
  REGISTER_TEST(otbExtractROI);
  REGISTER_TEST(otbFunctionToImageFilterNew);
  REGISTER_TEST(otbImageListToImageListFilterNew);
  REGISTER_TEST(otbImageListToImageListApplyFilterNew);
  REGISTER_TEST(otbVectorImageToASImageAdaptorNew);
  REGISTER_TEST(otbImageListToVectorImageFilter);
  REGISTER_TEST(otbImageAndVectorImageOperationFilterTest);
  REGISTER_TEST(otbImageOfVectorsToMonoChannelExtractROI);
  REGISTER_TEST(otbImageListNew);
  REGISTER_TEST(otbImageOfVectorsToMonoChannelExtractROINew);
  REGISTER_TEST(otbExtractROINew);
  REGISTER_TEST(otbImageListToVectorImageFilter2);
  REGISTER_TEST(otbExtractROI_RGB);
  REGISTER_TEST(otbComplexToIntensityFilterTest);
  REGISTER_TEST(otbStandardFilterWatcherNew);
  REGISTER_TEST(otbMultiToMonoChannelExtractROINew);
  REGISTER_TEST(otbMultiToMonoChannelExtractROI);
  REGISTER_TEST(otbImageTest);
  REGISTER_TEST(otbFlexibleDistanceWithMissingValueNew);
  REGISTER_TEST(otbImageFunctionAdaptorNew);
  REGISTER_TEST(otbImageFunctionAdaptor);
  REGISTER_TEST(otbStandardWriterWatcher);
  REGISTER_TEST(otbMultiChannelExtractROINew);
}
