#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbLikelihoodPathListFilter);
  REGISTER_TEST(otbParallelLinePathListFilterNew);
  REGISTER_TEST(otbRemoveWrongDirectionFilter);
  REGISTER_TEST(otbSimplifyPathListFilter);
  REGISTER_TEST(otbRoadExtractionFilterNew);
  REGISTER_TEST(otbRemoveIsolatedByDirectionFilterNew);
  REGISTER_TEST(otbAlignImageToPath);
  REGISTER_TEST(otbNonMaxRemovalByDirectionFilterNew);
  REGISTER_TEST(otbNeighborhoodScalarProductFilterNew);
  REGISTER_TEST(otbRemoveTortuousPathListFilterNew);
  REGISTER_TEST(otbNonMaxRemovalByDirectionFilter);
  REGISTER_TEST(otbRemoveWrongDirectionFilterNew);
  REGISTER_TEST(otbRoadExtractionFilter);
  REGISTER_TEST(otbLinkPathListFilter);
  REGISTER_TEST(otbModulusAndDirectionImageFiltersNew);
  REGISTER_TEST(otbSimplifyPathListFilterNew);
  REGISTER_TEST(otbRemoveTortuousPathListFilter);
  REGISTER_TEST(otbLinkPathListFilterNew);
  REGISTER_TEST(otbLikelihoodPathListFilterNew);
  REGISTER_TEST(otbParallelLinePathListFilter);
  REGISTER_TEST(otbRemoveIsolatedByDirectionFilter);
  REGISTER_TEST(otbVectorDataToRoadDescriptionFilterNew);
  REGISTER_TEST(otbVectorDataToRoadDescriptionFilter);
  REGISTER_TEST(otbSimplifyManyPathListFilter);
  REGISTER_TEST(otbNeighborhoodScalarProductFilter);
  REGISTER_TEST(otbDrawPathAlign);
}
