#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbSpectralSensitivityReaderNew);
  REGISTER_TEST(otbSpectralSensitivityReaderTest);
  REGISTER_TEST(otbSpectralSensitivityReaderGenericTest);
  REGISTER_TEST(otbReflectanceToImageImageFilter);
  REGISTER_TEST(otbReflectanceToLuminanceImageFilterNew);
  REGISTER_TEST(otbLuminanceToReflectanceImageFilterNew);
  REGISTER_TEST(otbLuminanceToReflectanceImageFilterAuto);
  REGISTER_TEST(otbImageToLuminanceImageFilterNew);
  REGISTER_TEST(otbLandsatTMSpectralRuleBasedClassifierTest);
  REGISTER_TEST(otbRadiometryCorrectionParametersToAtmosphericRadiativeTermsNew);
  REGISTER_TEST(otbLuminanceToImageImageFilterAuto);
  REGISTER_TEST(otbLuminanceToImageImageFilterNew);
  REGISTER_TEST(otbReflectanceToLuminanceImageFilterAuto);
  REGISTER_TEST(otbAeronetExtractDataBadData);
  REGISTER_TEST(otbRomaniaReflectanceToRomaniaSurfaceReflectanceImageFilter);
  REGISTER_TEST(otbRadiometryCorrectionParametersToAtmosphericRadiativeTerms);
  REGISTER_TEST(otbSurfaceAdjacencyEffectCorrectionSchemeFilterNew);
  REGISTER_TEST(otbImageToReflectanceImageFilterAuto);
  REGISTER_TEST(otbAtmosphericCorrectionParametersNew);
  REGISTER_TEST(otbImageToReflectanceImageFilterNew);
  REGISTER_TEST(otbFilterFunctionValuesNew);
  REGISTER_TEST(otbWavelengthSpectralBandsNew);
  REGISTER_TEST(otbAtmosphericRadiativeTermsNew);
  REGISTER_TEST(otbAtmosphericRadiativeTermsSingleChannelNew);
  REGISTER_TEST(otbAtmosphericRadiativeTermsTest);
  REGISTER_TEST(otbImageToReflectanceImageFilter);
  REGISTER_TEST(otbLuminanceToReflectanceImageFilter);
  REGISTER_TEST(otbReflectanceToImageImageFilterAuto);
  REGISTER_TEST(otbAeronetNew);
  REGISTER_TEST(otbAeronetExtractData);
  REGISTER_TEST(otbReflectanceToSurfaceReflectanceImageFilterNew);
  REGISTER_TEST(otbReflectanceToSurfaceReflectanceImageFilterTest);
  REGISTER_TEST(otbReflectanceToSurfaceReflectanceImageFilterTest2);
  REGISTER_TEST(otbImageMetadataCorrectionParametersNew);
  REGISTER_TEST(otbImageToLuminanceImageFilterAuto);
  REGISTER_TEST(otbAtmosphericCorrectionSequencementTest);
  REGISTER_TEST(otbSIXSTraitsTest);
  REGISTER_TEST(otbSIXSTraitsComputeAtmosphericParametersTest);
  REGISTER_TEST(otbReflectanceToImageImageFilterNew);
  REGISTER_TEST(otbSurfaceAdjacencyEffectCorrectionSchemeFilter);
  REGISTER_TEST(otbLuminanceToImageImageFilter);
  REGISTER_TEST(otbReflectanceToLuminanceImageFilter);
  REGISTER_TEST(otbImageToLuminanceImageFilter);
}
