extern int otb_6s_otb_6s__(
  otb_6s_doublereal *otb_asol__,
  otb_6s_doublereal *otb_phi0__,
  otb_6s_doublereal *otb_avis__,
  otb_6s_doublereal *otb_phiv__,
  otb_6s_integer *otb_month__,
  otb_6s_integer *otb_jday__,
  otb_6s_doublereal *otb_pressure__,
  otb_6s_doublereal *otb_uw__,
  otb_6s_doublereal *otb_uo3__,
  otb_6s_integer *otb_iaer__,
  otb_6s_doublereal *otb_taer55__,
  otb_6s_doublereal *otb_wlinf__,
  otb_6s_doublereal *otb_wlsup__,
  otb_6s_doublereal *otb_s__,
  otb_6s_doublereal *otb_ratm__,
  otb_6s_doublereal *otb_sast__,
  otb_6s_doublereal *otb_tgasm__,
  otb_6s_doublereal *otb_sdtott__,
  otb_6s_doublereal *otb_sutott__,
  otb_6s_doublereal *otb_tdif_up__,
  otb_6s_doublereal *otb_tdir_up__,
  otb_6s_doublereal *otb_tdif_up_ray__,
  otb_6s_doublereal *otb_tdif_up_aer__
  );
