extern int otb_6s_ssssss_otb_main_function( otb_6s_real *otb_asol__, 
otb_6s_real *otb_phi0__, 
otb_6s_real *otb_avis__, 
otb_6s_real *otb_phiv__, 
otb_6s_integer *otb_month__, 
otb_6s_integer *otb_jday__, 
otb_6s_real *otb_pressure__, 
otb_6s_real *otb_uw__, 
otb_6s_real *otb_uo3__, 
otb_6s_integer *otb_iaer__, 
otb_6s_real *otb_taer55__, 
otb_6s_real *otb_wlinf__, 
otb_6s_real *otb_wlsup__, 
otb_6s_real *otb_s__, 
otb_6s_real *otb_ratm__, 
otb_6s_real *otb_sast__, 
otb_6s_real *otb_tgasm__, 
otb_6s_real *otb_sdtott__, 
otb_6s_real *otb_sutott__
);
