
OBJ	=	CACCoder.obj CACDecoder.obj CACModel.obj CVLCCoder.obj CVLCDecoder.obj CWBlock.obj CWTCoder.obj CWTDecoder.obj CompressWT.obj

EXTRAFLAGS = 	-I..\Inc -I..\..\Inc -I..\..\..\DISE -D"WIN32"

GDAL_ROOT	=	..\..\..\..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
	copy *.obj ..\..\..\..\..\o

clean:
	-del *.obj

