#!/bin/sh

BUNDLE="`echo "$0" | sed -e 's/\/Contents\/MacOS\/.*//'`"
RESOURCES="$BUNDLE/Contents/Resources"

#echo "BUNDLE: $BUNDLE"
#echo "RESOURCES: $RESOURCES"

export GDAL_DATA=$RESOURCES/share/gdal
export ITK_AUTOLOAD_PATH=$RESSOURCES/lib/otb/applications

cd $HOME

exec "$RESOURCES/bin/monteverdi2"
