#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbCompacityPathRectangle);
  REGISTER_TEST(otbVectorizationPathListFilterNew);
  REGISTER_TEST(otbRegionImageToRectangularPathListFilterNew);
  REGISTER_TEST(otbImageToEdgePathFilter);
  REGISTER_TEST(otbCompacityPathCircle);
  REGISTER_TEST(otbDrawPathListFilterWithValue);
  REGISTER_TEST(otbImageFittingPolygonListFilterNew);
  REGISTER_TEST(otbDrawPathDessinCarre);
  REGISTER_TEST(otbCompacityPathSquare);
  REGISTER_TEST(otbPathLengthFunctor);
  REGISTER_TEST(otbPathListToHistogramGenerator);
  REGISTER_TEST(otbImageFittingPolygonListFilter);
  REGISTER_TEST(otbImageToPathFilterNew);
  REGISTER_TEST(otbImageToEdgePathFilterNew);
  REGISTER_TEST(otbDrawPathListFilter);
  REGISTER_TEST(otbDrawPathListFilterNew);
  REGISTER_TEST(otbDrawPathFilter);
  REGISTER_TEST(otbOrientationPath);
  REGISTER_TEST(otbOrientationPathNew);
  REGISTER_TEST(otbDrawPathFilterNew);
  REGISTER_TEST(otbPolyLineImageConstIterator);
  REGISTER_TEST(otbRegionImageToRectangularPathListFilter);
  REGISTER_TEST(otbVectorizationPathListFilter);
  REGISTER_TEST(otbPathListToPathListFilterNew);
  REGISTER_TEST(otbPathListToHistogramGeneratorNew);
  REGISTER_TEST(otbCompacityPathNew);
  REGISTER_TEST(otbClosePathFunctor);
  REGISTER_TEST(otbPolyLineImageIterator);
}
