//*******************************************************************
//
// License:  See top level LICENSE.txt file.
// 
// Author: Garrett Potts (gpotts@imagelinks.com)
// 
//********************************************************************
// $Id: ossimRpfConstants.h 9967 2006-11-29 02:01:23Z gpotts $
//
#ifndef ossimRpfComponentId_HEADER
#define ossimRpfComponentId_HEADER

const unsigned long OSSIM_RPF_ULONG_NULL = 0xFFFFFFFF;

enum ossimRpfComponentId
{
   OSSIM_RPF_HEADER_COMPONENT   = 128,
   OSSIM_RPF_LOCATION_COMPONENT = 129,
   OSSIM_RPF_COVERAGE_SECTION_SUBHEADER = 130,
   OSSIM_RPF_COMPRESSION_SECTION_SUBHEADER = 131,
   OSSIM_RPF_COMPRESION_LOOKUP_SUBSECTION = 132,
   OSSIM_RPF_COMPRESION_PARAMETER_SUBSECTION = 133,
   OSSIM_RPF_COLOR_GRAYSCALE_SECTION_SUBHEADER = 134,
   OSSIM_RPF_COLORMAP_SUBSECTION = 135,
   OSSIM_RPF_IMAGE_DESCRIPTION_SUBHEADER = 136,
   OSSIM_RPF_IMAGE_DISPLAY_PARAMETERS_SUBHEADER = 137,
   OSSIM_RPF_MASK_SUBSECTION = 138,
   OSSIM_RPF_COLOR_CONVERTER_SUBSECTION = 139,
   OSSIM_RPF_SPATIAL_DATA_SUBSECTION = 140,
   OSSIM_RPF_ATTRIBUTE_SECTION_SUBHEADER = 141,
   OSSIM_RPF_ATTRIBUTE_SUBSECTION = 142,
   OSSIM_RPF_EXPLICIT_AREAL_COVERAGE_TABLE = 143,
   OSSIM_RPF_RELATED_IMAGES_SECTION_SUBHEADER = 144,
   OSSIM_RPF_RELATED_IMAGES_SUBSECTION = 145,
   OSSIM_RPF_REPLACE_UPDATE_SECTION_SUBHEADER = 146,
   OSSIM_RPF_REPLACE_UPDATE_TABLE = 147,
   OSSIM_RPF_BOUNDARY_RECT_SECTION_SUBHEADER = 148,
   OSSIM_RPF_BOUNDARY_RECT_TABLE = 149,
   OSSIM_RPF_FRAME_FILE_INDEX_SECTION_SUBHEADER = 150,
   OSSIM_RPF_FRAME_FILE_INDEX_SUBSECTION = 151,
   OSSIM_RPF_COLOR_TABLE_INDEX_SECTION_SUBHEADER = 152,
   OSSIM_RPF_COLOR_TABLE_INDEX_RECORD = 153
};

#endif
