SET( CMAKE_BUILD_TYPE "Debug" CACHE STRING "debianDebug" FORCE )
SET( OTB_USE_CURL "ON" CACHE STRING "debianDebug" FORCE )
SET( USE_FFTWD "ON" CACHE STRING "debianDebug" FORCE )
SET( USE_FFTWF "ON" CACHE STRING "debianDebug" FORCE )

