
SET(OSGEO4W_FOUND FALSE)
IF(WIN32)

  FIND_PATH(OSGEO4W_ROOT NAMES OSGeo4W.bat PATHS $ENV{OSGEO4W_ROOT} )

  IF(OSGEO4W_ROOT)
		SET(CMAKE_INCLUDE_PATH ${OSGEO4W_ROOT}/include;${CMAKE_INCLUDE_PATH})
    SET(CMAKE_LIBRARY_PATH ${OSGEO4W_ROOT}/lib;${CMAKE_LIBRARY_PATH})
    SET(OSGEO4W_FOUND TRUE)
		MESSAGE(STATUS "Found OSGeo4W (${OSGEO4W_ROOT})")
	ELSE(OSGEO4W_ROOT)
		MESSAGE(STATUS "Could not find OSGeo4W")
	ENDIF(OSGEO4W_ROOT)
	
ENDIF(WIN32)
