/*=========================================================================

Program:   ORFEO Toolbox
Language:  C++
Date:      $Date$
Version:   $Revision$


Copyright (c) Centre National d'Etudes Spatiales. All rights reserved.
See OTBCopyright.txt for details.

Copyright (c) CS Systemes d'information. All rights reserved.
See CSCopyright.txt for details.

This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.

=========================================================================*/
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <string>
#include <iostream>
#include <vector>

/**
 * @brief main application for generating the otb.conf file.
 *
 * @param argv[1] Path to OTB_BINARY_DIR/otb.conf
 *
 * @param argv[2] language parameter
 */
int main(int argc, char* argv[])
{
   const unsigned int nbParameters = 3;

   std::ofstream os(argv[1]); 
   if (!os)
   {
      exit(1);
   }

   std::vector <std::string>  paramVector;
   
   /** write available parameters to a vector */
   for (unsigned int i=0;i<nbParameters;++i)
   {
     if ( argc >= ( i+3 ) )
     {
       /** Get the default parameter (from cmake)*/
       paramVector.push_back( argv[i+2] );
     }
     else
     {
       /** Set param="" if the parameter is not available*/
       paramVector.push_back("");
     }
   }
   /** Write parameters to the configuration file*/
   os << "#Auto generated by config-properties \n"
      << "OTB_LANG="
      <<  paramVector[0]
      << "\n"
      << "OTB_STREAM_IMAGE_SIZE_TO_ACTIVATE_STREAMING="
      <<  paramVector[1]
      << "\n"
      << "OTB_STREAM_MAX_SIZE_BUFFER_FOR_STREAMING="
      <<  paramVector[2]
      << "\n"
      << "#End of config file properties generation"
      << std::endl;
   
   os.close();

   std::cout << "wrote file: " << argv[1] << std::endl;

   exit(0);
}
