message(STATUS "Importing MuParser...")
find_package(MuParser)

if(MUPARSER_FOUND)
  option(OTB_USE_EXTERNAL_MUPARSER "Use external MuParser library." ON)
else(MUPARSER_FOUND)
  option(OTB_USE_EXTERNAL_MUPARSER "Use external MuParser library." OFF)
  set(MUPARSER_LIBRARIES otbmuparser)
endif(MUPARSER_FOUND)
mark_as_advanced(OTB_USE_EXTERNAL_MUPARSER)
