MESSAGE(STATUS "Importing Ossim...")
# Option for internal/external GDAL
OPTION(OTB_USE_EXTERNAL_OSSIM "Use an outside build of Ossim." OFF)
MARK_AS_ADVANCED(OTB_USE_EXTERNAL_OSSIM)

IF(OTB_USE_EXTERNAL_OSSIM)
  FIND_PACKAGE(Ossim REQUIRED)
ELSE(OTB_USE_EXTERNAL_OSSIM)
  SET(OSSIM_LIBRARIES otbossim)
ENDIF(OTB_USE_EXTERNAL_OSSIM)
