message(STATUS "Importing MuParser...")
find_package(MuParser)

if(MUPARSER_FOUND)
  option(OTB_USE_EXTERNAL_MUPARSER "Use external MuParser library." ON)
else()
  option(OTB_USE_EXTERNAL_MUPARSER "Use external MuParser library." OFF)
  set(MUPARSER_LIBRARIES otbmuparser)
  message(STATUS "Using MuParser internal version")
endif()
mark_as_advanced(OTB_USE_EXTERNAL_MUPARSER)
