MESSAGE(STATUS "Importing Jpeg2000...")
# Use the openjpeg library.
OPTION(OTB_USE_JPEG2000 "Use to support jpeg2000 image file format." ON)
MARK_AS_ADVANCED(OTB_USE_JPEG2000)

IF(OTB_USE_JPEG2000)
 MESSAGE(STATUS "  Enabling Jpeg2000 support")
 
 SET(OPENJPEG_SOURCE_DIR ${OTB_SOURCE_DIR}/Utilities/otbopenjpeg)
 SET(OPENJPEG_BINARY_DIR ${OTB_BINARY_DIR}/Utilities/otbopenjpeg)
 
 SET(OPENJPEG_NAMESPACE "OTBOPENJPEG")
 SET(OPJ_MANGLE_PREFIX "otbopenjpeg")
 SET(OPENJPEG_INSTALL_LIB_DIR ${OTB_INSTALL_LIB_DIR_CM24})

  IF(NOT BUILD_SHARED_LIBS)
        ADD_DEFINITIONS(-DOPJ_STATIC)
  ENDIF(NOT BUILD_SHARED_LIBS)
  
ELSE( OTB_USE_JPEG2000 )
  MESSAGE(STATUS "  Disabling Jpeg2000 support")
ENDIF(OTB_USE_JPEG2000)
