# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _kmlengine
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class Bbox(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bbox, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bbox, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _kmlengine.new_Bbox(*args)
        try: self.this.append(this)
        except: self.this = this
    def Contains(*args): return _kmlengine.Bbox_Contains(*args)
    def ExpandLatitude(*args): return _kmlengine.Bbox_ExpandLatitude(*args)
    def ExpandLongitude(*args): return _kmlengine.Bbox_ExpandLongitude(*args)
    __swig_destroy__ = _kmlengine.delete_Bbox
    __del__ = lambda self : None;
Bbox_swigregister = _kmlengine.Bbox_swigregister
Bbox_swigregister(Bbox)

Clone = _kmlengine.Clone
GetFeatureLatLon = _kmlengine.GetFeatureLatLon
GetRootFeature = _kmlengine.GetRootFeature
class KmlFile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KmlFile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KmlFile, name)
    def __init__(self, *args, **kwargs): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_getmethods__["CreateFromParse"] = lambda x: _kmlengine.KmlFile_CreateFromParse
    if _newclass:CreateFromParse = staticmethod(_kmlengine.KmlFile_CreateFromParse)
    def root(*args): return _kmlengine.KmlFile_root(*args)
    def GetObjectById(*args): return _kmlengine.KmlFile_GetObjectById(*args)
    __swig_destroy__ = _kmlengine.delete_KmlFile
    __del__ = lambda self : None;
KmlFile_swigregister = _kmlengine.KmlFile_swigregister
KmlFile_swigregister(KmlFile)
KmlFile_CreateFromParse = _kmlengine.KmlFile_CreateFromParse

KmzSplit = _kmlengine.KmzSplit
SplitUri = _kmlengine.SplitUri


