#include "otbTestMain.h"
void RegisterTests()
{
  REGISTER_TEST(otbSVMImageClassificationWithRuleFilter);
  REGISTER_TEST(otbLabelMapSVMClassifierNew);
  REGISTER_TEST(otbLabelMapSVMClassifier);
  REGISTER_TEST(otbSVMPointSetModelEstimatorTrain);
  REGISTER_TEST(otbExhaustiveExponentialOptimizerNew);
  REGISTER_TEST(otbSVMImageModelEstimatorModelAccessor);
  REGISTER_TEST(otbSVMImageClassificationFilter);
  REGISTER_TEST(otbSVMModelNew);
  REGISTER_TEST(otbSVMImageModelEstimatorNew);
  REGISTER_TEST(otbSVMImageModelEstimatorTrainOneClass);
  REGISTER_TEST(otbSVMCrossValidationCostFunctionNew);
  REGISTER_TEST(otbSVMModelLoadSave);
  REGISTER_TEST(otbSVMClassifierPointSet);
  REGISTER_TEST(otbSVMImageClassificationWithRuleFilterNew);
  REGISTER_TEST(otbSVMImageModelEstimatorTrain);
  REGISTER_TEST(otbObjectDetectionClassifierNew);
  REGISTER_TEST(otbObjectDetectionClassifier);
  REGISTER_TEST(otbSVMClassifierImage);
  REGISTER_TEST(otbSVMClassifierNew);
  REGISTER_TEST(otbSVMSampleListModelEstimatorNew);
  REGISTER_TEST(otbSVMSampleListModelEstimatorTest);
  REGISTER_TEST(otbSVMModelAccessor);
  REGISTER_TEST(otbSVMModelLoad);
  REGISTER_TEST(otbSVMImageClassificationFilterNew);
  REGISTER_TEST(otbSVMPointSetModelEstimatorNew);
  REGISTER_TEST(otbSVMMarginSamplerNew);
  REGISTER_TEST(otbExhaustiveExponentialOptimizerTest);
}
